branches:
  only:
    - master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CXXFLAGS: /std:c++14
      CMAKE_GENERATOR: 15

platform: x64

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - git clone https://github.com/Microsoft/vcpkg c:\projects\vcpkg
  - set VCPKG_ROOT=c:\projects\vcpkg
  - cd %VCPKG_ROOT%
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install libpq sqlite3
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - cmake -G "Visual Studio %CMAKE_GENERATOR% Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake
  - cmake --build . --config Release
